apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-flask
  template:
    metadata:
      labels:
        app: devops-flask
    spec:
      containers:
        - name: devops-flask-container
          image: devops-flask-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
