apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-flask
  template:
    metadata:
      labels:
        app: devops-flask
    spec:
      containers:
        - name: devops-flask-container
          image: ghcr.io/vikas-202/containerized-flask-application:3eeca4894edeac736e91ed6e5729f405d2083cf0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
